### ISSUE TITLE
[Feat] TextReplacement UI 추후작업 및 SwiftData 데이터 리팩토링

### ISSUE THREAD

**Issue by MADElinessss** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#118]
### 📝 작업 목적
| ⚒️ Title | `[Feat] TextReplacement UI 추후작업 및 SwiftData 데이터 리팩토링` | 
| :--- | :--- |
| 📜 **Description** | [ TextReplacement UI 머지 이후에 해야 했던 추후작업들, SwiftData 데이터 리팩토링 |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link]() |

---

### 🛠️ Tasks

매 TODO
- [x] ConversationView에 들어갈 CustomToolBar 위치 조정 필요합니다. 디자인도 수정해야할수도있어요 -> 첼란
- [x]  TKTextReplacementListview에 들어갈 서치바 -> 배경색 적용이 왜 안될까,,sos
- [x]  ListView, AddView, EditView 쫌쫌따리 UI 수정
- [x]  SettingViewStore 수정 -> 리앤
- [ ]  SwiftData Manager에 텍대 기능 병합
