### ISSUE TITLE
[Fix] 모카의 디자인 UIUX 피드백 반영

### ISSUE THREAD

**Issue by MADElinessss** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#124]
### 📝 작업 목적
| ⚒️ Title | `[Fix] 모카의 디자인 UIUX 피드백 반영` | 
| :--- | :--- |
| 📜 **Description** | [Fix] 모카의 디자인 UIUX 피드백 반영합니다. store 잘 사용해가면서 수정할게여 |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link]() |

---

### 🛠️ Tasks

TR 디자인 수정

- [x]  키보드 내리기 다 적용안되어있음
- [x]  텍대 타이틀 넣어야지
- [x]  ~~검색 눌렀다가, 다른데 누르면 키보드 사라지게~~
- [x]  취소 누르면 키보드 내리기
- [x]  검색 없을때 텅뷰
    - [x]  목차가 왜 올라가지 없애기
- [x]  검색 입력안했을때는 x버튼 사라지게 → 모든 텍필에 적용하기!!
    - [x]  텍필 height 44, R값 22
    - [x]  focusState → 아예 흰뷰
- [x]  버튼 사이즈(height 고정, horizontal padding)
- [x]  알럿 색 안맞음 + 뒤에 어둡게 처리 + 버튼 길이가 다름
- [x]  edit: 변경사항없을때 저장 버튼 비활성화하기
- [x]  ~~인덱스 시도해보고 안되면~~ #을 먼저
- [x]  editview에서 텍필 둘다 0글자일때 글자수 한 글자 이상 이상 써달라는 메세지로 바꾸기
    - [x]  0글자일때 비활성화
- [x]  editview 버튼 키보드 아래로 가게 시도. 안되면 모카가 패딩값 넣어준대
- [ ]  영어 돌아오게 해..
- [x]  미니로도 확인해보기
