### ISSUE TITLE
[Fix] Settings 관련 뷰 수정사항 반영

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#125]
### 📝 작업 목적
| ⚒️ Title | `Settings 관련 뷰 수정사항 반영` | 
| :--- | :--- |
| 📜 **Description** | description |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link]() |

---

### 🛠️ Tasks

- [x] 설정 - 리스트 앱 정보 항목 삭제 및 대체
- [x] 자잘한 UI 디테일 - 다크모드 대응, 백버튼 라벨 수정
- [x] 설정 - 안내 문구
	- [x] 토글 기능 UserDefaults  저장 안됨 문제
	- [x] 타이틀, 토글 여부 UserDefaults 데이터 연결
	- [x] 텍스트 없을 때 countLimit 빨강색 입혀지고 미리보기 disable
	- [x] 안내 문구 사용 토글이 false일 때 문구 편집 disable
- [x] 설정 - 메일뷰 - 메일 안거치고 바로 메일 쏴지게.. 모카의 앱 참고
