### ISSUE TITLE
[Fix] 1.0.0 Settings에서 제외된 부분 추가 (안내 문구, 접근성, 실험실)

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#158]
### 📝 작업 목적
| ⚒️ Title | `1.0.0 Settings에서 제외된 부분 추가` | 
| :--- | :--- |
| 📜 **Description** | description |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link]() |

---
### 🛠️ Tasks

- [ ] 권한 분기처리 연결
* [x] 안내 문구 뷰 추가 
* [x] 접근성 뷰 수정 및 추가
* [ ] 실험실 뷰 수정 및 추가
