### ISSUE TITLE
[Fix] Settings&Main View 관련 디자인 UI 수정 사항 Fix

### ISSUE THREAD

**Issue by MADElinessss** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#164]
### 📝 작업 목적
| ⚒️ Title | `디자인 UI 수정 사항들 Fix` | 
| :--- | :--- |
| 📜 **Description** | Main & Settings 관련 모카의 디자인 피드백들을 반영합니다. 뷰 단위로 그룹 나눠서 올리겠습니다.  |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link]() |

---

### 🛠️ Tasks

Settings

- [x] ‼️ 설정 진입 시 툴바 관련 View Extension 추가!!!!!
- [x] 커스텀 툴바 없는 뷰에 다 추가해씀

- S100
- [x]  Allway로고 다크모드용 커스텀 에셋으로 교체
- [x]  팀원 이모지 Circle 색상 BG_Alert로 변경
- S10
- [x]  툴바와 콘텐츠 사이 패딩 20 적용 필요
- [x]  텍스트 bold 처리
- [x]  설정 리스트 헤더(대화, 정보, 지원) leading패딩 24
- [x]  리스트는 horizontal패딩 16
- S93
    - [x]  툴바 타이틀 달기
- S110
    - [x]  툴바 타이틀 달기
- S111
    - [x]  이메일 오타 수정
        - allway.team01인데, allway.team01a로 되어있음.

Main

- [x]  히스토리 및 설정 심볼 커스텀 에셋으로 변경
- [x]  좌상단 로고 신규 로고 - 다크 추가
- [x]  위치 라벨 bold로 변경 → text 디자인시스템 적용 후 수정하기!
