### ISSUE TITLE
[Fix] Conversation View 관련 디자인 UI 수정 사항 Fix

### ISSUE THREAD

**Issue by MADElinessss** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#166]
### 📝 작업 목적
| ⚒️ Title | `Conversation View 관련 디자인 UI 수정 사항 Fix` | 
| :--- | :--- |
| 📜 **Description** | 모카와 Conversation View 관련 디자인 UI 수정 사항 Fix |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link]() |

---

### 🛠️ Tasks

- **컨버세이션**
- 🟠 [x] TypingView 컴포넌트 색 변경기준: <focusState>에서 <textfield가 비어있는지 검사 후 비어있지 않으면,>으로 변경!
```swift
// TKConversationViewStore
 public func isTextFieldEmpty() -> Bool {
```

 - C10
- [x]  텍필focusing일때랑 아닐때 전체지우기 버튼 동일하게 비활성 색상으로 교체 필요.
- GR4, GR3
 - [ ]  메인에서 C10으로 진입시 자동으로 텍필 focusing되게끔 수정필요.
- [x]  툴바 디자인 1.1버전으로 변경됨.
- [x]  툴바와 아래 텍필 컴포넌트들과 패딩값도 변경됨.
- [x]  툴바 버튼들 사이즈 피그마랑 달라서 확인 필요.
- [x]  C10-10 텍스트필드 영역 확대. 🆘
    - 톡버튼 top padding 32잡고 그 위로 싹다 텍필 영역으로 터치해서 키보드 띄울 수 있도록.
- [x]  C10-20 가이딩뷰 Divider 삭제.
- [x]  C10-30 듣고있어요 라벨 백그라운드 사이즈 다름.
- [ ]  C10-30 듣고있어요 우측 Circle 버튼 아님.
- [ ]  C10-31 신규 구현.
    - 타이핑 없이 Showing넘어갈 경우 텅 멘트 기본 적용.
- [ ]  아무것도 타이핑 하지 않았을 때 저장 비활성화. -> 🟠 디자인 수정 없이?

 - C11
- [ ]  C11-10 텍필 누를때 위 답변영역 움찔하는거 고정필요.
- [ ]  툴바 디자인 1.1버전으로 변경됨. (C10과 색상 다름 + 쉐브론 유무)
- [x]  쉐브론 다크모드에서도 white로 구현되어야함.
- [ ]  C11-13 신규 구현.
    - 이전 답변이 없을 경우 텅 멘트가 opacity0.5로 들어감.
- [x]  텍필focusing일때랑 아닐때 전체지우기 버튼 동일하게 비활성 색상으로 교체 필요.
    - GR4, GR3
- [ ]  RepeatTyping화면으로 왔을때 자동으로 텍필 focusing되게끔 수정필요.
- C12
    - [ ]  시트 높이 변경 (더 낮아짐)
- [x]  위치 라벨이 툴바 타이틀로 이동됨.
- C13 신규 구현
    - 대화 취소할 때 Alert 구현. (기능+디자인)
- C30-10
- [ ]  기존 대화에서 이어할 경우 기존 대화 타이틀 표기.
    - 1.1버전 신규 디자인 적용.
