### ISSUE TITLE
[Feat] TextReplacement 기능 보완

### ISSUE THREAD

**Issue by MADElinessss** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#189]
### 📝 작업 목적
| ⚒️ Title | `TextReplacement 기능 보완` | 
| :--- | :--- |
| 📜 **Description** | TextReplacement 기능 보완합니다.. |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link]() |

---

### 🛠️ Tasks

대체적으로 디자인 수정과 정렬 안되던 문제를 해결할 예정입니다~

- C40 텍스트대치 툴바
    - [ ]  C40-12가 원래 텍대 색상인데 C40-11로 색상 교체 예정~
        - 1.1버전 신규 적용 사항.
    - [ ]  C40-10 모두지우기 버튼 비활성화시 색상 변경
        - 1.1버전 신규 적용 사항.

- S20-10
    - [ ]  텅뷰 심볼 수정
        - bubble.left.and.text.bubble.right.fill
        - width: 117, height: 96
    - [ ]  인덱싱 오류 수정
        - ㄹ 인덱싱이 ㅃ
        - ㅇ 인덱싱이 ㅎ
        - ㅁ 인덱싱이 ㅌ
        - 모음만 입력했을 때 전체적으로 인덱싱 몬가 잘못됌…
    - [ ]  검색창 누를때 프리징 발생.
- S20-11
    - [ ]  검색중일때 +버튼 비활성화
    - [ ]  S20-11 검색 텅뷰 구현
    - [ ]  텍필에 아무것도 없을 때 우측 X버튼 안뜨게 수정
    - [ ]  검색 텍필 등장할때 히스토리검색텍필처럼 트랜지션 적용
- S21
    - [ ]  변환문구 작성할 때 텍필 사이즈 안늘어남.
- S22
    - [ ]  텍대 삭제버튼 사이즈 수정
    - [ ]  S22-30 알럿 버튼 사이즈 똑같이 조정
    - [ ]  S22-30 알럿 떠있을 때 툴바 비활성화 및 Dim처리 필요.
    - [ ]  단축어/변환문구 최대 텍스트 입력 또는 미입력시 footnote색상 red로 변경
- [ ]  C10 타이핑에서 텍대 쓸 때 텍대 한번 쓰고 띄어쓰기 안하면 다른 텍대 안뜸.
