### ISSUE TITLE
[ver 1.1.1] 업데이트 사항 정리

### ISSUE THREAD

**Issue by ValseLee** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#222]
### 📝 작업 목적
| ⚒️ Title | `업데이트 사항 정리` | 
| :--- | :--- |
| 📜 **Description** | description |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | _ |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | _ |

---

### 🛠️ Tasks

* [x] Transcript 누수 해결
* [x] TextReplacement 시트의 백그라운드 이슈 해결
* [x] 그외 사항 논의 필요

**Comment by MADElinessss** [comment]
TextReplacement 시트의 백그라운드 이슈 는 무엇인가요..?

**Comment by ValseLee** [comment]
> TextReplacement 시트의 백그라운드 이슈 는 무엇인가요..?

아악 저거 백그라운드 컬러 관련 이슈였어요 제가 전에 잡앗습니다
