### ISSUE TITLE
[Fix] ConversationView 디자인 QA 내역 반영

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#228]
### 📝 작업 목적
| ⚒️ Title | `ConversationView 디자인 QA 내역 반영` | 
| :--- | :--- |
| 📜 **Description** | 첼란한테 넘겨받은 ConversationView 디자인 관련 수정작업을 진행합니다. |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link](https://www.notion.so/yenchoichoi/ALLWAY-0829d236200943d3b31ee9920a15c8ca?p=f860630c00c145ec99795ce076562ef9&pm=s) |

---

### 🛠️ Tasks

* [ ] C10-10: 텍스트 커서 길이 텍스트 크기에 맞추어 height 25px로 수정
* [x] C10-12: Typing 텍스트 박스 영역 스크롤 없이 8줄 확보
* [x] C10-30: Showing 텍스트 영역 스크롤 없이 160자 전부 보일 수 있도록
* [x] C10-40: 1. showing 영역 & Listening 영역 둘다 312px 로 동일한 영역 사이즈
    - [x] 2. Showing 영역 스크롤 없이 160자 전부 보이도록
    - [x] 3. C10-50으로 트랜지션 될 때 모카가 이야기한 배경 애니메이션 수정
