### ISSUE TITLE
[Fix] TextReplacementView&SettingView 디자인 QA 내역 반영

### ISSUE THREAD

**Issue by MADElinessss** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#230]
### 📝 작업 목적
| ⚒️ Title | `TextReplacementView 디자인 QA 내역 반영` | 
| :--- | :--- |
| 📜 **Description** | QA 시트에서 텍대 파트 및 설정 뷰에서 현시점에서 할 수 있는 부분 해보겠습니다! |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link]() |

---

### 🛠️ Tasks
**TextReplacementView**
- 모카의 핫픽스 요청 - 줄바꿈시 공백 나타나는 버그 수정
* [x] 검색필드 클릭했을 때 애니메이션 히스토리뷰와 동일하게 수정
* [x] 타이핑 전 포커스 상태에서는 텅뷰 에셋 삭제"
* [ ] 첫 화면은 에러 피드백 삭제
**Setting GuideMessage**
* [x] 안내문구 OFF일 시 '안내문구 편집' 아이템 투명도 30%로 업데이트
**Setting Makers**
* [x] 올웨이 소개 본문 굵기 Medium으로 업데이트
* [x] 리스트 아이템 컴포넌트 1.0 반영
