### ISSUE TITLE
[Feat] Localization

### ISSUE THREAD

**Issue by MADElinessss** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#234]
### 📝 작업 목적
| ⚒️ Title | `Localization` | 
| :--- | :--- |
| 📜 **Description** | 올해의 앱이 되어봅시다 !!! |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link]() |

---

### 🛠️ Tasks

- [x]  신난 마음 가라앉히기
- [x]  각 String Type → 영어 번역
    - [x]  단어 문화 차이 고려할 것
    - [x]  Date Format 수정
    - [x]  영어버전 - 폰트 크기, UI 확인
- [x]  코드 각 String Type → 다국어
- [x]  info plist → 다국어
- [x]  String Catalog 활용해서 빠진 부분 검토
