### ISSUE TITLE
[ver 1.2.0] 업데이트 사항 정리 

### ISSUE THREAD

**Issue by ValseLee** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#238]
### 📝 작업 목적
| ⚒️ Title | `업데이트 사항 정리` | 
| :--- | :--- |
| 📜 **Description** | ver 1.2.0 업데이트 사항 정리 |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | _ |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | _ |

---

### 🛠️ Tasks

* [x] Localization
* [x] Conversation Flow 정리
* [x] 개인정보 처리 방침 분기처리
* [x] 메일 오류 해결
