### ISSUE TITLE
[Fix] DarkMode 대응, History 관련 QA 버그 픽스

### ISSUE THREAD

**Issue by MADElinessss** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#242]
### 📝 작업 목적
| ⚒️ Title | `DarkMode 대응, History 관련 QA 버그 픽스` | 
| :--- | :--- |
| 📜 **Description** |  |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link]() |

---

### 🛠️ Tasks

* [ ] 1. 날짜와 시간 정보 둘다 semibold로 수정 필요 
* [ ] 2. STT버블 오른쪽 여백이 없어야 함
* [ ] 3. 다크모드 색상 (온보딩~히스토리~세팅)
