### ISSUE TITLE
[Feat] 뷰 스크롤 트랜지션 구현

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#36]
### 📝 작업 목적
| ⚒️ Title | `인트로 -> 히스토리 뷰 스크롤 트랜지션 구현` | 
| :--- | :--- |
| 📜 **Description** | 인트로 -> 히스토리 뷰 스크롤 트랜지션을 ScrollViewReader와 GeometryReader를 사용해 구현합니다. |
| ![](https://img.shields.io/badge/-black?logo=figma)**Figma** | [Link]() |
| ![](https://img.shields.io/badge/-black?logo=notion)**Notion Card** | [Link]() |

---

### 🛠️ Tasks

* [x] 인트로 -> 히스토리 뷰 스크롤 뼈대 구현 (ScrollViewReader, GeometryReader)
   * [x] UI 레이아웃 조정
* [x] 스와이프 안내 메세지 트랜지션 및 애니메이션 구현
   * [x] 스와이프 타입 enum으로 분리
* [x] 일반 스크롤 -> 가속화된 트랜지션 구현 (제스쳐 사용)
   * [x] 제스쳐 영역 및 스와이프 안내 메세지 UI 재배치 (overlay 사용)
* [x] 중첩 스크롤 방지 (히스토리뷰 스크롤만 enable)
* [x] 뷰, 스토어 분리 작업
