### ISSUE TITLE
[TODO] TECH TODOS

### ISSUE THREAD

**Issue by ValseLee** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#37]
## 🛠️ Tasks
- Talklat 개발 상황 및 개발 예정 목록들에 대한 개괄적인 사항들을 리스트업합니다.
- Comment로 추가적인 Todo와 Task들을 추가할 수 있습니다.
- 각 작업에 대한 이슈 넘버를 태그합니다.

> UNTIL INTERNAL SHOW CASE
* [ ] `TKHistoryView` Scroll transition into `TKIntroView` \ #36
* [ ] STT Live Haptic, Mode Switch Haptic Feedback \ #28 #34 

> AFTER INTERNAL SHOW CASE
* [ ] Design System -> Component -> View Layout \ #15 #29 #17 #16 
* [ ] Animation & Transition \ #23 #20 
* [ ] Speech & Accelerate \ #18 

> BACKLOGS
* [ ] GitHub Action Flow -> Auto Build, Auto PR Merge
* [ ] App Clips
