### ISSUE TITLE
[Refactor] TKWritingView, TKHistoryView, TKRecordingView의 코드를 이어보아요.

### ISSUE THREAD

**Issue by MADElinessss** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#41]
### 📝 작업 목적
| ⚒️ Title | Refactoring History Related Parts | 
| :--- | :--- |
| 📜 **Description** | TKWritingView, TKHistoryView, TKRecordingView의 코드를 이어보아요. |
| ![](https://img.shields.io/badge/-black?logo=figma)**Figma** | [Link]() |
| ![](https://img.shields.io/badge/-black?logo=notion)**Notion Card** | [Link]() |

---

### 🛠️ Tasks

* [x] TKWritingView에 있는 텍스트 필드를 디자인 시스템 적용 버전으로 적용합니다.
* [x] TKHistoryView에 들어갈 부분도 이어줍니다. 
* [x] TKHistoryView에서 데이터를 Model로 뺍니다.
* [x] 디자인팀과 텍스트필드 플레이스홀더 글자 수 제한, 줄 제한, 고정 멘트 등에 대해 상의해봅니다. -> 160
* [x] 기존 placeholder 잘못 구현된 부분 수정(2줄 Placeholder가 아니었음ㅠㅠ)
* [x] RecordingView 음성인식 transcript 한 줄로 출력되는것 수정
* [x] RecordingView, WritingView 텍스트 뒤 배경 각각 조건에 맞게 넣기(RecordingView는 음성인식 시작 시)
* [x] WrtingView 키보드 없애는 코드 추가

<아래 내용 새 이슈에서 작업할게요>
* [ ] RecordingView 내에서 기존 대답 텍스트의 위치나 속성 변하면서 -> (모카가 원하는 transition) animation 넣기 ㅠㅠ
* [ ] linespacing 다시 점검(모카님 요청)
* [x] 전체 지우기 텍스트 입력시 색 바뀌는거

**Comment by MADElinessss** [comment]
ㅠㅠ이것저것 수정할게 보이니까 뷰 코드가 깔끔했던 첼란 코드에서 제가 막 흩어놓는 것 같아 마음이 아프군요,,잘 수습해보겠음,,

**Comment by ValseLee** [comment]
돈워리 킵고잉

**Comment by ValseLee** [comment]
그런데 tasklist에 이해되지 않는 게 있어서 나중에 추가 논의를 조금 해봅시당

**Comment by ValseLee** [comment]
라이브 설명 완료
1. 하나의 이슈에서 너무 많은 작업을 수행하지 않기 -> revert의 어려움, 작업 단위가 커지며 작업 속도가 느려짐 등
2. 수행해야 하는 태스크 구체저으로 쓰기
