### ISSUE TITLE
[Fix] 스크롤 전환 및 히스토리 뷰 버그 수정

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#46]
### 📝 작업 목적
| ⚒️ Title | `title` | 
| :--- | :--- |
| 📜 **Description** | description |
| ![](https://img.shields.io/badge/-black?logo=figma)**Figma** | [Link]() |
| ![](https://img.shields.io/badge/-black?logo=notion)**Notion Card** | [Link]() |

---

### 🛠️ Tasks

P1

* [x] 히스토리 들어갔다 나오면 히스토리 naviTitle이 그대로 존재하는 버그가 있어요! @lianne-b
* [x] 5번 버그가 발생한 이후 메인뷰랑 히스토리뷰가 분리되지 않고 하나의 스크롤뷰로 되어버려요! @lianne-b
* [x] STT화면에서 히스토리뷰로 넘어갈 수 있는 버그가 있어요! @lianne-b (STT화면에서는 스크롤 방어해야 함!)

P2

* [ ] 히스토리뷰의 초기화면이 가장 하단이어야 해요! @lianne-b

P3

* [x] 초기 화면이랑 STT화면에서 상단에 안내메시지랑 쉐브론이 없어야 해요! @lianne-b

**Comment by lianne-b** [comment]
~스프린트1을 끝으로 작업 잠정 중단~ (뷰 디자인 수정 예정)
