### ISSUE TITLE
[Feat] TKRecordingView 첫번째 대화 이후 안내문구 변경

### ISSUE THREAD

**Issue by MADElinessss** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#52]
### 📝 작업 목적
| ⚒️ Title | `TKRecordingView 첫번째 대화 이후 안내문구 변경` | 
| :--- | :--- |
| 📜 **Description** | TKRecordingView 첫번째 대화 이후 안내문구를 "음성 인식을 위해 또박또박 크게   말해주세요."로 변경 |
| ![](https://img.shields.io/badge/-black?logo=figma)**Figma** | [Link]() |
| ![](https://img.shields.io/badge/-black?logo=notion)**Notion Card** | [Link]() |

---

### 🛠️ Tasks

* [ ] TKRecordingView 첫번째 대화 이후인지 판단할 수 있는 코드 작성
* [ ] GUIDE_MESSAGE에 두번째 이후 가이드메세지 추가 "음성 인식을 위해 또박또박 크게 말해주세요."
* [ ] 첫번째 대화 이후 안내문구 변경
