### ISSUE TITLE
[Feat] TKCommunicationView 구현

### ISSUE THREAD

**Issue by ValseLee** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#63]
### 📝 작업 목적
| ⚒️ Title | `TKCommunicationView 구현` | 
| :--- | :--- |
| 📜 **Description** | TKWritingView와 TKRecordingView를 처리하는 CommunicationView를 구현합니다. |
| ![](https://img.shields.io/badge/-black?logo=figma)**Figma** | _ |
| ![](https://img.shields.io/badge/-black?logo=notion)**Notion Card** | _ |

---

### 🛠️ Tasks

* [x] ~~View의 컴포넌트 단위를 관리하는 Presenter 구현~~
  * [x] `TKCommunicationView` 내부에서 ViewBuilder extension으로 정리
* [x] Animation & Transition 대응
* [x] UI 변동사항 적용하기
  * [x] fontsize 통일
  * [x] Gray Çolor 적용

**Comment by ValseLee** [comment]
Lo-Fi Stage -> Mid-Fi Stage
- 컬러 톤 정리중
- Animation과 View 변화 대응 필요
