### ISSUE TITLE
[Feat] TKCommunicationView -> TKConversationView 전환

### ISSUE THREAD

**Issue by ValseLee** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#70]
### 📝 작업 목적
| ⚒️ Title | `TKCommunicationView -> TKConversationView 전환` | 
| :--- | :--- |
| 📜 **Description** | TKCommunicationView를 TKConversationView로 전환하는 작업을 합니다. |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link](https://www.figma.com/file/Mb450yYTvio6Q9y6d0otwv/%F0%9F%8D%8EALLWAY-Team?type=design&node-id=1113-2943&mode=design) |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | _ |

---

### 🛠️ Tasks

* [ ] TKCommunicationView를 ViewID에 맞춘 TKConversationView로 수정합니다.
* [ ] TKGuidingView를 중간 단계에 삽입합니다.
  * [ ] Recording과 Writing 사이에 GuidingView! #69 
  * [ ] Button과 Flip 제스처를 분리하여 UX 정의
