### ISSUE TITLE
[Feat] Location Store 구현

### ISSUE THREAD

**Issue by alpaka99** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#71]
### 📝 작업 목적
| ⚒️ Title | `Location Store를 구현합니다.` | 
| :--- | :--- |
| 📜 **Description** |Location관련 여러가지 기능을 구현합니다 |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link](https://www.notion.so/yenchoichoi/CoreLocation-8d2e5313bbd24aee9c396562f20e3e33)
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link]() |

---

### 🛠️ Tasks

* [ ] Location Store를 생성합니다(첼란식 Key-Component로 구현 도전)
* [ ] Location을 저장할 기본적인 함수들 구현
* [ ] SwiftData와 연결하는 작업 추후 @lianne-b와 함
