### ISSUE TITLE
[Feat] Voice & SpeechToText Feature

### ISSUE THREAD

**Issue by MADElinessss** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#8]
### 📝 작업 목적
| ⚒️ Title | `Voice & SpeechToText feature` | 
| :--- | :--- |
| 📜 **Description** | `STT 기능을 구현합니다.` |
| ![](https://img.shields.io/badge/-black?logo=figma)**Figma** | (https://www.figma.com/file/Mb450yYTvio6Q9y6d0otwv/%F0%9F%8D%8EALLWAY-Team?type=design&node-id=555%3A2025&mode=design&t=om36ZAhqHVFjsaVJ-1) |
| ![](https://img.shields.io/badge/-black?logo=notion)**Notion Card** | `Link` |

---

### 🛠️ Tasks

* [x] STT 기본 기능을 구현합니다. 인식 정도(정확도)를 고려하면서 만들어요.
* [x] text를 화면에 띄웁니다.
* [ ] 허용 권한 만들고 리앤이랑 분기처리 맞추기
