### ISSUE TITLE
[Feat] SwiftData 모델 및 CRUD 메서드 구현

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#84]
### 📝 작업 목적
| ⚒️ Title | `SwiftData 모델 및 CRUD 메서드 구현` | 
| :--- | :--- |
| 📜 **Description** | History, Location, 대체 텍스트에서 쓰일 SwiftData의 틀을 구축합니다. |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | - |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link](https://www.notion.so/yenchoichoi/SwiftData-e5416d3092f14151954ea84c39868e34) |

---

### 🛠️ Tasks

* [x] 데이터 모델 구현
* [ ] 공통 CRUD 매니저 구현
* [ ] 프리뷰용 데이터 구조체 생성
