### ISSUE TITLE
[Feat] HistoryView 내부 구현하기

### ISSUE THREAD

**Issue by alpaka99** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#88]
### 📝 작업 목적
| ⚒️ Title | `HistoryView 내부 구현하기` | 
| :--- | :--- |
| 📜 **Description** | HistoryView 내부를 요구사항에 맞게 구현합니다 |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link](https://www.notion.so/yenchoichoi/HistoryView-907b1c5af9d040d8995b120c12e4af57) |

---

### 🛠️ Tasks

* [x] HistoryView 내부 대화내용에 관한 UI구현
* [ ] HistoryPreview, HistoryItemView에 맞게 나눠서 구현
* [x] 내부 기능적, UI적 디테일 구현
