### ISSUE TITLE
[Feat] TKMainView 구현

### ISSUE THREAD

**Issue by ValseLee** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#92]
### 📝 작업 목적
| ⚒️ Title | `TKMainView 구현` | 
| :--- | :--- |
| 📜 **Description** | TKMainView를 구현합니다. |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link](https://www.figma.com/file/Mb450yYTvio6Q9y6d0otwv/%F0%9F%8D%8EALLWAY-Team?type=design&node-id=1-5&mode=design) |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | _ |

---

### 🛠️ Tasks

* [ ] hi-fi TKMainView 구현
  * [ ] Button에 GeometryEffect 구현해보기
  * [ ] 하단 model sheet에 대한 User Interaction 분기처리 필요
* [ ] MainViewStore구현
