### ISSUE TITLE
[Feat] TextReplacement CRUD related UI 구현

### ISSUE THREAD

**Issue by MADElinessss** [DeveloperAcademy-POSTECH/MacC-Team-ALLWAY#97]
### 📝 작업 목적
| ⚒️ Title | `텍스트 대치 CRUD 관련 UI 작업` | 
| :--- | :--- |
| 📜 **Description** | 텍스트 대치 CRUD 관련 UI 작업 |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/a42c6a40-0f1d-4372-9c9c-967d44803665" width='20'> **Figma** | [Link]() |
| <img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-ALLWAY/assets/82270058/c7f9920d-e975-4ed7-ad83-7e6e08611463" width='20'> **Notion** | [Link]() |

---

### 🛠️ Tasks

(🥐 표시: 우선순위가 높고, 나머지는 우선순위가 낮습니다)
**다음 작업들 크게 텍대 CRUD 인데, 하나의 이슈에서 할지 여러개로 나눠서 할지 조언 부탁드립니다 🙏🏻**

**ConversationView**
- [ ]  🥐 커스텀 툴바 UI
**TestTKSettingView**
- [ ]  🥐 텍대 저장하는 UI 수정
- [x]  🥐 헤더 기존(단축어) → (ㄱㄴㄷABC)
- [x]  목차 - 레퍼런스 샤라웃 투 리앤 @lianne-b 
- [ ]  검색
- [ ]  텅 화면
**AddTextReplacementView**
- [ ]  🥐 단축어: 제한 - 한줄? 기준을 어떻게 하지?
- [ ]  🥐 변환 문구: 160자 제한
- 텍대 편집뷰 -> 안만듦
- [ ]  🥐 UI
- [ ]  🥐 여기에서만 D
- [ ]  🥐 삭제 알럿
